[build]
  publish = "public"
  command = "hugo --gc --minify"
  
[build.environment]
  HUGO_VERSION = "0.73.0"
  HUGO_ENV = "production"

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "public"
  exclude = [
    '**/**/*.jpg',
    '**/**/*.png',
    '**/**/*.svg',
    '**/**/*.jpeg'
  ]

[[plugins]]
package = "netlify-plugin-hashfiles"

  [plugins.inputs]
  entryPoints = [
    "*.jpg",
    "*.png",
    "*.jpeg",
    "*.svg"
  ]

[[plugins]]
package = "netlify-plugin-image-optim"

[[plugins]]
  package = "netlify-plugin-minify-html"

  [plugins.inputs]
    contexts = [
      'production'
    ]

  [plugins.inputs.minifierOptions]
    removeComments = true
    collapseInlineTagWhitespace = false